name = "whitenoise"

[builders]
"docker:go" = { enabled = true, enable_go_build_cache = true }
"exec:go"   = { enabled = true }

[runners]
"local:docker"  = { enabled = true }
"local:exec"    = { enabled = true }

[global.build_config]
  enable_go_build_cache = true

[[testcases]]
name = "transfer"
instances = { min = 2, max = 2, default = 2 }

  [testcases.params]
  size      = { type = "string", desc = "size of payload to transfer", default = "32MiB" }
  linkshape = { type = "object", desc = "serialized link shape configuration" }
  interrupt = { type = "string", desc = "connection interruption probability every N seconds; format: 0.2/5s", default = "0/0" }
